# Generated by Django 5.2.9 on 2026-01-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_operations', '0006_projectrole_projectuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_planning.flowfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_folders', to='company_operations.project')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('project', 'path')},
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SAVED', 'Saved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='company_operations.project')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='project_planning.flowfolder')),
            ],
        ),
        migrations.CreateModel(
            name='FlowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('steps_json', models.JSONField()),
                ('created_from_version', models.PositiveIntegerField(blank=True, help_text='Source version for rollback/copy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='project_planning.flow')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_planning.testcasefolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_folders', to='company_operations.project')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SAVED', 'Saved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('current_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='company_operations.project')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='project_planning.testcasefolder')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('pre_conditions_json', models.JSONField(default=list)),
                ('steps_json', models.JSONField(default=list)),
                ('expected_outcomes_json', models.JSONField(default=list)),
                ('created_from_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='project_planning.testcase')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('project', 'folder', 'name'), name='uniq_flow_name_per_folder'),
        ),
        migrations.AlterUniqueTogether(
            name='flowversion',
            unique_together={('flow', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='testcasefolder',
            unique_together={('project', 'path')},
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='testcaseversion',
            unique_together={('test_case', 'version_number')},
        ),
    ]
