# Generated by Django 5.2.9 on 2026-01-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0006_projectrole_projectuser'),
        ('project_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_planning.variablefolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_folders', to='company_operations.project')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('project', 'path')},
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='company_operations.project')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variables', to='project_planning.variablefolder')),
            ],
            options={
                'unique_together': {('project', 'key')},
            },
        ),
    ]
