# Generated by Django 5.2.9 on 2026-01-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_planning', '0003_elementfolder_element_elementlocator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together=set(),
        ),
    ]
