# Generated by Django 5.2.9 on 2026-02-21 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0010_remove_project_bdd_import_enabled'),
        ('project_planning', '0006_localtestcasefolder_localtestcase_testsuite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('project', 'name')},
        ),
        migrations.AddField(
            model_name='localtestcase',
            name='sequence_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_test_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcase',
            name='sequence_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='localtestcase',
            unique_together={('owner', 'sequence_id')},
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('owner', 'sequence_id'), ('project', 'name')},
        ),
        migrations.CreateModel(
            name='UserSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_sequence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
