# Generated by Django 5.2.9 on 2026-02-21 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0010_remove_project_bdd_import_enabled'),
        ('project_planning', '0007_alter_testcase_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localtestcase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('project', 'name')},
        ),
        migrations.CreateModel(
            name='TestCaseIdentity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('GLOBAL', 'Global'), ('LOCAL', 'Local')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_identities', to='company_operations.project')),
            ],
            options={
                'verbose_name_plural': 'Test Case Identities',
            },
        ),
        migrations.DeleteModel(
            name='UserSequence',
        ),
        migrations.RemoveField(
            model_name='localtestcase',
            name='sequence_id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='sequence_id',
        ),
    ]
