# Generated by Django 5.2.9 on 2026-02-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_auth', '0002_initial'),
        ('company_operations', '0008_project_template_needs_approval_and_more'),
        ('project_planning', '0004_alter_element_options_alter_element_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningEntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('level_order', models.PositiveIntegerField()),
                ('allow_children', models.BooleanField(default=True)),
                ('allow_execution_binding', models.BooleanField(default=False)),
                ('allow_dependencies', models.BooleanField(default=False)),
                ('allow_time_tracking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='EntityFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('user', 'User'), ('multi_user', 'Multi User'), ('boolean', 'Boolean'), ('json', 'JSON')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('is_execution_field', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options_json', models.JSONField(blank=True, null=True)),
                ('default_value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='test_plan.planningentitytype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_planning_items', to='company_operations.projectuser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planning_items', to='company_operations.projectuser')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_items', to='test_plan.planningentitytype')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_planning_items', to='company_operations.projectuser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='test_plan.planningitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_items', to='company_operations.project')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('BLOCKS', 'Blocks'), ('RELATES', 'Relates To')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='test_plan.planningitem')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='test_plan.planningitem')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_mode', models.CharField(blank=True, max_length=100)),
                ('auto_trigger', models.BooleanField(default=False)),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_planning.flow')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_planning.testcase')),
                ('planning_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_binding', to='test_plan.planningitem')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningItemFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_json', models.JSONField()),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_plan.entityfielddefinition')),
                ('planning_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='test_plan.planningitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVAL_PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('CREATED', 'Created'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_templates', to='company_auth.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_process_templates', to='company_auth.companyuser')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_process_templates', to='company_auth.companyuser')),
            ],
        ),
        migrations.AddField(
            model_name='planningentitytype',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_types', to='test_plan.processtemplate'),
        ),
        migrations.CreateModel(
            name='TimeTrackingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('STATUS_CHANGE', 'On Status Change'), ('EXECUTION_START', 'On Execution Start')], max_length=50)),
                ('stop_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('STATUS_CHANGE', 'On Status Change'), ('EXECUTION_END', 'On Execution End')], max_length=50)),
                ('allow_multiple_sessions', models.BooleanField(default=False)),
                ('entity_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking_rule', to='test_plan.planningentitytype')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('planning_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='test_plan.planningitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_operations.projectuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definition', to='test_plan.planningentitytype')),
            ],
        ),
        migrations.AddField(
            model_name='planningentitytype',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_types', to='test_plan.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_final', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='test_plan.workflowdefinition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='initial_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='test_plan.workflowstate'),
        ),
        migrations.AddField(
            model_name='planningitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_plan.workflowstate'),
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='test_plan.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='test_plan.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='test_plan.workflowdefinition')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='planningentitytype',
            unique_together={('template', 'level_order')},
        ),
    ]
