# Generated by Django 5.2.9 on 2026-02-07 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0008_project_template_needs_approval_and_more'),
        ('test_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlanningConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_level_1_name', models.CharField(blank=True, max_length=255)),
                ('entity_level_2_name', models.CharField(blank=True, max_length=255)),
                ('entity_level_3_name', models.CharField(blank=True, max_length=255)),
                ('entity_level_4_name', models.CharField(blank=True, max_length=255)),
                ('entity_level_5_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_config', to='company_operations.project')),
            ],
        ),
    ]
