# Generated by Django 5.2.9 on 2026-02-07 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_auth', '0002_initial'),
        ('company_operations', '0008_project_template_needs_approval_and_more'),
        ('test_plan', '0002_projectplanningconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplateBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activated_templates', to='company_auth.companyuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_bindings', to='company_operations.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_bindings', to='test_plan.processtemplate')),
            ],
            options={
                'unique_together': {('project', 'template')},
            },
        ),
    ]
