# Generated by Django 5.2.9 on 2026-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plan', '0003_projecttemplatebinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtemplate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVAL_PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('CREATED', 'Created'), ('REJECTED', 'Rejected'), ('ACTIVATED', 'Activated')], default='DRAFT', max_length=30),
        ),
    ]
