# Generated by Django 5.2.9 on 2026-02-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_auth', '0002_initial'),
        ('company_operations', '0008_project_template_needs_approval_and_more'),
        ('test_plan', '0004_alter_processtemplate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_group_by', models.CharField(default='STATUS', max_length=20)),
                ('theme', models.CharField(default='modern', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='company_operations.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningBoardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_by', models.CharField(blank=True, max_length=20, null=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='test_plan.planningboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_preferences', to='company_auth.companyuser')),
            ],
            options={
                'unique_together': {('user', 'board')},
            },
        ),
    ]
