# Generated by Django 5.2.9 on 2026-02-14 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plan', '0005_planningboard_planningboardpreference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planningboardpreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='planningboardpreference',
            name='board',
        ),
        migrations.RemoveField(
            model_name='planningboardpreference',
            name='user',
        ),
        migrations.CreateModel(
            name='KanbanBoardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(choices=[('STANDARD', 'Standard'), ('COMPACT', 'Compact'), ('DETAIL', 'Detail')], default='STANDARD', max_length=50)),
                ('color_scheme', models.JSONField(blank=True, default=dict)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('visibility_settings', models.JSONField(blank=True, default=dict)),
                ('default_card_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_config', to='test_plan.processtemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='PlanningBoard',
        ),
        migrations.DeleteModel(
            name='PlanningBoardPreference',
        ),
    ]
