# Generated by Django 5.2.9 on 2026-02-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0008_project_template_needs_approval_and_more'),
        ('test_plan', '0006_remove_planningboardpreference_board_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanbanboardconfig',
            old_name='column_mapping',
            new_name='columns_config',
        ),
        migrations.RemoveField(
            model_name='kanbanboardconfig',
            name='default_card_fields',
        ),
        migrations.RemoveField(
            model_name='kanbanboardconfig',
            name='template',
        ),
        migrations.RemoveField(
            model_name='kanbanboardconfig',
            name='visibility_settings',
        ),
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_config', to='company_operations.project'),
        ),
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='show_due_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='show_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kanbanboardconfig',
            name='color_scheme',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('MODERN', 'Modern-Dark'), ('HIGH_CONTRAST', 'High-Contrast')], default='MODERN', max_length=50),
        ),
        migrations.AlterField(
            model_name='kanbanboardconfig',
            name='layout_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('COMPACT', 'Compact'), ('USER_GROUPED', 'Grouped by User')], default='STANDARD', max_length=50),
        ),
    ]
