# Generated by Django 5.2.9 on 2026-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_plan', '0007_rename_column_mapping_kanbanboardconfig_columns_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='card_density',
            field=models.CharField(choices=[('COMPACT', 'Compact'), ('COMFORTABLE', 'Comfortable'), ('SPACIOUS', 'Spacious')], default='COMFORTABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='custom_accent_color',
            field=models.CharField(default='#7c5cff', max_length=7),
        ),
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='enable_glass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='swimlane_attribute',
            field=models.CharField(choices=[('NONE', 'None'), ('OWNER', 'Assignee'), ('PRIORITY', 'Priority')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='zoom_level',
            field=models.IntegerField(default=100),
        ),
    ]
