# Generated by Django 5.2.9 on 2026-02-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0008_project_template_needs_approval_and_more'),
        ('test_plan', '0008_kanbanboardconfig_card_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='context_key',
            field=models.CharField(db_index=True, default='TEMPLATES', max_length=50),
        ),
        migrations.AlterField(
            model_name='kanbanboardconfig',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_configs', to='company_operations.project'),
        ),
    ]
