# Generated by Django 5.2.9 on 2026-02-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0008_project_template_needs_approval_and_more'),
        ('test_plan', '0009_kanbanboardconfig_context_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboardconfig',
            name='view_key',
            field=models.CharField(default='GLOBAL', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='kanbanboardconfig',
            unique_together={('project', 'view_key')},
        ),
        migrations.AlterField(
            model_name='kanbanboardconfig',
            name='swimlane_attribute',
            field=models.CharField(choices=[('NONE', 'None'), ('OWNER', 'Assignee'), ('PRIORITY', 'Priority'), ('SECTION', 'Section')], default='NONE', max_length=20),
        ),
        migrations.RemoveField(
            model_name='kanbanboardconfig',
            name='context_key',
        ),
    ]
