# Generated by Django 5.2.9 on 2026-02-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_plan', '0011_add_testplan_plancycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='template',
        ),
        migrations.RemoveField(
            model_name='planningitem',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planningitem',
            name='is_draft',
        ),
        migrations.DeleteModel(
            name='PlanCycle',
        ),
        migrations.DeleteModel(
            name='TestPlan',
        ),
    ]
