# Generated by Django 5.2.9 on 2025-12-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_team_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
