# Generated by Django 5.2.9 on 2025-12-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0002_project_max_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='max_members',
        ),
    ]
