# Generated by Django 5.2.9 on 2025-12-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0003_remove_project_max_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_team_members',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
