# Generated by Django 5.2.9 on 2026-01-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0004_alter_project_max_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='builder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='can_configure_processes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='execution_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='flows_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='reports_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='test_cases_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
