# Generated by Django 5.2.9 on 2026-01-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_auth', '0002_initial'),
        ('company_operations', '0005_project_builder_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='company_operations.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='company_auth.companyuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='company_operations.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company_operations.projectrole')),
            ],
            options={
                'unique_together': {('project', 'company_user')},
            },
        ),
    ]
