# Generated by Django 5.2.9 on 2026-01-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0006_projectrole_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='element_capture_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
