# Generated by Django 5.2.9 on 2026-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0007_project_element_capture_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template_needs_approval',
            field=models.BooleanField(default=False, help_text='Require template approval before activation.'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_planning_enabled',
            field=models.BooleanField(default=False, help_text='Enable Test Planning module for this project.'),
        ),
    ]
