# Generated by Django 5.2.9 on 2026-02-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0008_project_template_needs_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bdd_import_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
