# Generated by Django 5.2.9 on 2026-02-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_operations', '0009_project_bdd_import_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bdd_import_enabled',
        ),
    ]
